spring:
  application:
    name: crypto-market-service
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
